project:
  type: website

website:
  title: "ISS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
    - text: "Take-Home Exercises"
      menu:
        - text: "Take-Home Exercise 1"
          href: ""

    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
        
date: "April 24, 2025"
date-modified: "last-modified"

format:
  html:
    theme: zephyr
    css: styles.css
    fontsize: 1.1em
    toc: true
    toc-location: left

editor: visual
execute:
  eval: true
  echo: true
  warning: false
  freeze: true

