project:
  type: website

website:
  favicon: "images/Chibi-guy.png"
  title: "ISS608-VAA"
  navbar:
    logo: "images/Chibi-guy.png"
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Exercise 8"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "Hands-on Exercise 9"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
        - text: "Hands-on Exercise 10"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
    - text: "Take-Home Exercises"
      menu:
        - text: "Take-Home Exercise 1"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
        - text: "Take-Home Exercise 1 Part 2"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01_Part2.html"
        - text: "Take-Home Exercise 2"
          href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html"
        - text: "Take-Home Exercise 3"
          href: "Take-Home_Ex/Take-Home_Ex03/Take-Home_Ex03.html"
    - text: "In-Class Exercises"
      menu:
        - text: "In-Class Exercise 5"
          href: "In-class_Ex/In-class_Ex05/MC1_In-class_Ex05.html"

    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
        
date: "April 24, 2025"
date-modified: "last-modified"

format:
  html:
    theme: zephyr
    css: styles.css
    fontsize: 1.1em
    toc: true
    toc-location: left

editor: visual
execute:
  eval: true
  echo: true
  warning: false
  freeze: true

